ucs build for version greater 1.8
NetKnights-GmbH/privacyidea-ucs-saml pull request #8
Opened 2021-03-16 11:03 UTC by laclaro

2021-03-16 11:04 UTC, laclaro commented on Makefile
> +	if [ ${VERSION_NUMBER} -ge 19 ]; then \
does not work for 1.10

2021-03-16 11:11 UTC, spaceone requested changes
Please don't use the variable `baseConfig` anymore. It's deprecated since ages, will be removed in UCS 5.0, it is necessary for the upgrade to UCS 5.0 that it is not already used anymore. The variable `configRegistry` can be used instead.

2021-03-16 11:16 UTC, spaceone reviewed
btw. UCR has boolean variables.
Things like `configRegistry.is_true('privacyidea/saml/verifyhost')` would be possible instead of checking strings manually. UCS Administrators are also used to set values like yes/on/1/etc. which are also covered by `is_true() / is_false()`

2021-03-16 11:38 UTC, pablo-knight approved these changes
next step build debfile

2021-03-16 11:38 UTC, merged

2021-03-16 11:49 UTC, spaceone commented
@laclaro @pablo-knight Please don't ignore my review uncommented.

2021-03-18 11:19 UTC, laclaro commented
@spaceone Thank's for your hint. I change the method in #9